Cleanup secret.

diff --git a/bin/secret b/bin/secret
--- a/bin/secret
+++ b/bin/secret
@@ -1,20 +1,36 @@
 #!/bin/sh
 
+SUDO=/usr/bin/sudo
+
 cleanup () {
-	SVND=$1
-	MOUNT=$2
-	sudo vnconfig -u "${SVND}" > /dev/null 2>&1
-	sudo umount "${UMOUNT}" > /dev/null 2>&1
+    SVND=$1
+    MOUNT=$2
+    ${SUDO} umount "${UMOUNT}" > /dev/null 2>&1
+    ${SUDO} vnconfig -u "${SVND}" > /dev/null 2>&1
+}
+findsvnd () {
+    ${SUDO} vnconfig -l | while read LINE; do
+        case "${LINE}" in
+            *": not in use") set -- $LINE; echo ${1%:}; break;;
+        esac
+    done
 }
 SAFEDIR="${HOME}/.safe"
 SAFEIMG="${HOME}/.safe.img"
-SVND="s$(sudo vnconfig -l |\
-    sed -e '/not in use$/!d; s/:.*$//' | head -1)"
+
+SVND=$(findsvnd)
+[[ -n "${SVND}" ]] || (echo "no free (s)vnd devices"; exit 1)
+
 trap "cleanup ${SVND} ${SAFEDIR}" EXIT
-[ "${SVND}" != 's' ] || (echo "no free (s)vnd devices"; return 1)
-set -e
-sudo vnconfig -k "${SVND}" "${SAFEIMG}"
-sudo mount "/dev/${SVND}c" "${SAFEDIR}"
-vim "${SAFEDIR}"
-sudo umount "${SAFEDIR}"
-sudo vnconfig -u "${SVND}"
+echo ${SUDO} vnconfig -k "${SVND}" "${SAFEIMG}"
+exit
+RET=$?
+case "${RET}" in
+    0) ;;
+    1) echo "failed to decrypt ${SAFEIMG}"; exit 1;;
+    *) exit ${RET};;
+esac
+
+${SUDO} mount "/dev/${SVND}c" "${SAFEDIR}"
+${VISUAL} "${SAFEDIR}/passwords"
+cleanup "${SNVD}" "${SAFEDIR}"
