Rewrite shroot.

diff --git a/bin/shroot b/bin/shroot
--- a/bin/shroot
+++ b/bin/shroot
@@ -1,22 +1,33 @@
 #!/bin/sh -e
 
-CHROOTHOST=localhost
-CHROOTUSER=$(whoami)
-unset SETROOT
+# http://www.openbsd.org/faq/upgrade46.html#upgrade
+
+MERGE=0
+SKELETON=
+RELEASE=
+SETROOT=
+SUDO=/usr/bin/sudo
+SETEXT=.tgz
+SETS="xserv xfont xshare xbase game misc comp man base"
 
 usage () {
-    echo "mychroot [-H CHROOTHOST] [-s SETROOT] [-u CHROOTUSER] CHROOTDIR"
+    echo "$0 [-m] [-S SUDO] [-k SKELETON] [-r RELEASE] [-s SETROOT] CHROOTDIR"
 }
 
 say () {
     echo "===> $*"
 }
 
-error () {
+warn () {
     echo "=!=> $*"
 }
 
-makeabs () {
+fail () {
+    warn $*
+    exit 1
+}
+
+abspath () {
     OPWD="${PWD}"
     cd "$1"
     echo $PWD
@@ -24,54 +35,94 @@ makeabs () {
 }
 
 enter_chroot () {
-    ssh "${CHROOTUSER}@${CHROOTHOST}"
+    ARGS=${*:-/bin/ksh -l}
+    ${SUDO} chroot "${CHROOTDIR}" ${ARGS}
 }
 
 build_chroot () {
-    mkdir -p "${CHROOTDIR}"
-    for FILESET in "${SETROOT}"/*.tgz; do
-        say "Extracting $(basename ${FILESET})"
-        tar -xzp -C "${CHROOTDIR}" -f "${FILESET}"
+    for SET in ${SETS}; do
+        [ -n "${RELEASE}" ] && break
+        SETFILE=$(echo ${SETROOT}/${SET}*${SETEXT})
+        if [ -f "${SETFILE}" ]; then
+            RELEASE=${SETFILE##*${SET}}
+            RELEASE=${RELEASE%${SETEXT}}
+        fi
     done
-    
-    say "Installing kernels and ramdisk"
-    cp "${SETROOT}"/bsd* "${CHROOTDIR}/"
-    
+
+    if [ -z "${RELEASE}" ]; then
+        warn "You must specify a release"; usage; exit 1
+    fi
+
+    [ -d "${CHROOTDIR}" ] || ${SUDO} mkdir -p "${CHROOTDIR}"
+    CHROOTDIR="$(abspath "${CHROOTDIR}")"
+
+    say "Installing kernel"
+    cd "${CHROOTDIR}"
+    ${SUDO} rm -f obsd
+    [ -r bsd ] && ${SUDO} ln bsd obsd
+    ${SUDO} cp "${SETROOT}/bsd" nbsd && ${SUDO} mv nbsd bsd
+    [ -r ./sbin/reboot ] && ${SUDO} cp ./sbin/reboot ./sbin/oreboot
+    cd "${SETROOT}"
+    ${SUDO} cp bsd.rd bsd.mp "${CHROOTDIR}/."
+
+    ALLSETS="${SETS}"
+    if [ "${MERGE}" -eq 0 ]; then
+        ALLSETS="${SETS} etc xetc"
+    else
+        say "Not extracting etc${RELEASE}/xetc${RELEASE} -- merge later"
+    fi
+
+    for SET in ${ALLSETS}; do
+        SETFILE=${SET}${RELEASE}${SETEXT}
+        [ -r "${SETFILE}" ] || fail "Set ${SETFILE} not found in ${SETROOT}"
+        say "Extracting ${SETFILE}"
+        ${SUDO} tar -C "${CHROOTDIR}/" -xzphf "${SETFILE}"
+    done
+
     say "Running MAKEDEV"
-    cd "${CHROOTDIR}/dev"
-    ./MAKEDEV all >/dev/null
-    
-    say "Installing passwd and group files"
-    cp /etc/master.passwd /etc/group "${CHROOTDIR}"/etc/.
-    chroot "${CHROOTDIR}" pwd_mkdb -p /etc/master.passwd
+    cd "${CHROOTDIR}/dev" && ${SUDO} ./MAKEDEV all
+    cd "${SETROOT}"
+
+    say "Building password and group databases"
+    enter_chroot /usr/sbin/pwd_mkdb -p /etc/master.passwd
 
     say "Updating /etc/{localtime,resolv.conf}"
-    ln -sf "$(readlink /etc/localtime)" "${CHROOTDIR}/etc/localtime"
-    cp "/etc/resolv.conf" "${CHROOTDIR}/etc/resolv.conf"
-    
+    ${SUDO} ln -sf "$(readlink /etc/localtime)" "${CHROOTDIR}/etc/localtime"
+    ${SUDO} cp /etc/resolv.conf "${CHROOTDIR}/etc/resolv.conf"
+        
     say "Updating dev.db and ld.so.hints"
-    chroot "${CHROOTDIR}" dev_mkdb
-    chroot "${CHROOTDIR}" ldconfig /usr/lib /usr/local/lib /usr/X11R6/lib
+    enter_chroot /usr/sbin/dev_mkdb
+    enter_chroot /sbin/ldconfig /usr/lib /usr/local/lib /usr/X11R6/lib
+
+    if [ -x "${CHROOTDIR}/root/chroot.site" ]; then
+        say "Running /root/chroot.site"
+        enter_chroot /root/chroot.site
+    fi
+
+    if [ -n "${SKELETON}" -a -d "${SKELETON}" ]; then
+        say "Copying skeleton files"
+        ${SUDO} rsync -azr "${SKELETON}/" "${CHROOTDIR}/"
+    fi
+
 }
 
-while getopts H:hs:u: ARG; do
+while getopts mS:hk:r:s: ARG; do
     case "${ARG}" in
-        H) CHROOTHOST="${OPTARG}";;
-        s) SETROOT=$(makeabs "${OPTARG}");;
+        m) MERGE=1;;
+        S) SUDO="${OPTARG}";;
+        k) SKELETON=$(abspath "${OPTARG}");;
+        r) RELEASE="${OPTARG}";;
+        s) SETROOT=$(abspath "${OPTARG}");;
         *) usage; exit 1;;
     esac
 done
 
 shift $(($OPTIND - 1))
-CHROOTDIR=$(makeabs "$1")
+CHROOTDIR=$1
+shift
 
-if [ -z "${SETROOT}" ]; then
-    enter_chroot
-else
-    if [ "`id -u`" -ne 0 ]; then
-        error "need root privileges to run this script"
-        usage
-        exit 1
-    fi
+if [ -n "${SETROOT}" ]; then
     build_chroot
+else
+    enter_chroot $*
 fi
